version: '3.3'

services:
  bustimer:
    image: docker.io/library/bustimer-gateway
    container_name: bustimer
    restart: always
    ports:
      - "8080:8080"
#  mongodb:
#    image: mongo:latest
#    container_name: bustimer_mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: uhrqwr2q4u42ibfarwb
#    volumes:
#      - mongodb_data:/data/db
#    ports:
#      - 27017
#  mongo-express:
#    image: mongo-express
#    container_name: bustimer_mongo_express
#    restart: always
#    ports:
#      - 10001:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: uhrqwr2q4u42ibfarwb
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    depends_on:
#      - mongodb
#volumes:
#  mongodb_data: